import { GoogleGenAI, Type, Schema } from "@google/genai";
import { AnalysisResult } from "../types";

// Helper to convert File to Base64
export const fileToBase64 = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      const base64Data = base64String.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

const ARTICLE_TYPES = [
  "Review articles", "Research articles", "Encyclopedia", "Book chapters", 
  "Conference abstracts", "Book reviews", "Case reports", "Conference info", 
  "Correspondence", "Data articles", "Discussion", "Editorials", "Errata", 
  "Examinations", "Mini reviews", "News", "Patent reports", "Practice guidelines", 
  "Product reviews", "Short communications", "Software publications", "Video articles", "Other"
];

// We now pass the full definition {id, prompt} instead of just IDs
type ColumnDefinition = {
  id: string;
  prompt: string;
};

export const analyzePdf = async (
  fileInput: File | string, 
  columnsToAnalyze: ColumnDefinition[],
  apiKey: string,
  modelId: string = "gemini-1.5-flash"
): Promise<AnalysisResult> => {
  if (!apiKey) {
    throw new Error("API Key is missing. Please check your settings.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Handle both File object and direct Base64 string
  let base64Data: string;
  if (typeof fileInput === 'string') {
    base64Data = fileInput;
  } else {
    base64Data = await fileToBase64(fileInput);
  }

  // 1. Build Dynamic Prompt
  let instruction = `
    Analyze the provided academic research PDF.
    
    Part 1: Bibliographic Metadata (ALWAYS REQUIRED)
    Extract the following:
    - Title
    - Authors
    - Publication Year (or 'n/d' if not found)
    - DOI (Digital Object Identifier) or a direct URL to the paper.
    - Article Type. Categorize the paper into one of these types: ${ARTICLE_TYPES.join(", ")}.
  `;

  if (columnsToAnalyze.length > 0) {
    instruction += `\nPart 2: Specific Analysis\nFor the following aspects, extract the information:\n`;
    columnsToAnalyze.forEach(col => {
      instruction += `- ${col.id}: ${col.prompt}\n`;
    });
  }

  // 2. Build Dynamic Schema
  const properties: Record<string, Schema> = {
    metadata: {
      type: Type.OBJECT,
      properties: {
        title: { type: Type.STRING },
        authors: { type: Type.ARRAY, items: { type: Type.STRING } },
        publicationYear: { type: Type.STRING },
        doi: { type: Type.STRING, description: "The DOI or URL of the paper" },
        articleType: { type: Type.STRING, enum: ARTICLE_TYPES },
      },
      required: ["title", "authors"],
    }
  };

  const requiredFields = ["metadata"];

  // Add schema properties only for requested columns
  columnsToAnalyze.forEach(col => {
    // We treat 'results' specifically as an array if possible, otherwise strings
    if (col.id === 'results') {
         properties[col.id] = { type: Type.ARRAY, items: { type: Type.STRING } };
    } else {
         properties[col.id] = { type: Type.STRING };
    }
    requiredFields.push(col.id);
  });

  try {
    const response = await ai.models.generateContent({
      model: modelId,
      contents: {
        parts: [
          { inlineData: { mimeType: "application/pdf", data: base64Data } },
          { text: instruction },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: properties,
          required: requiredFields,
        },
      },
    });

    const text = response.text;
    if (!text) throw new Error("No response from Gemini");

    const result = JSON.parse(text) as AnalysisResult;
    
    // Inject Model Metadata (Watermark)
    result._models = {};
    
    // Mark metadata as generated by this model
    result._models['metadata'] = modelId;

    // Mark specific columns
    columnsToAnalyze.forEach(col => {
       if (result[col.id]) {
         result._models![col.id] = modelId;
       }
    });

    return result;

  } catch (error) {
    console.error("Gemini Analysis Error:", error);
    throw error;
  }
};